[project]
name = "a-maze-ing"
version = "0.1.0"
description = ""
authors = [
    {name = "Ahmed Alshoubaki",email = "ahmad7raed77@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
]

[dependency-groups]
dev = [
    "mypy (>=2.3.0,<3.0.0)",
    "flake8 (>=7.3.0,<8.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
